<br /><br />
<div id="view-content">
    <p>Apellido y nombre del solicitante: <?php echo $this->planilla['apellidoYnombreSolicitante']?></p>
    <p>dni: <?php echo $this->planilla['dniSolicitante']?></p>
    <p>Profesión/Ocupación/Plan Social: <?php echo $this->planilla['profSolicitante']?></p>
    <p>Ingresos Mensuales: <?php echo $this->planilla['ingresosSolicitante']?></p>
    <p>Apellido y nombre del el Cónyugue o Pareja: <?php echo $this->planilla['apellidoYNombreConSolicitante']?></p>
    <p>dni: <?php echo $this->planilla['dniConSolicitante']?></p>
    <p>Profesión/Ocupación/Plan Social: <?php echo $this->planilla['profConSolicitante']?></p>
    <p>Ingresos Mensuales: <?php echo $this->planilla['ingresosConSolicitante']?></p>
    <p>Otros Ingresos: <?php echo $this->planilla['otrosIngresosFinal']?></p>
    <p>Total Ingresos: <?php echo $this->planilla['totalIngresos']?></p>
    <p>N° APROS: <?php echo $this->planilla['apros']?></p>
    <p>Domicilio: <?php echo $this->planilla['domicilio']?></p>
    <p>Monto del subsidio solicitado $: <?php echo $this->planilla['montoDelSubsidio']?></p>
    <p>Destino del subsidio: <?php echo $this->planilla['destino']?></p>
    <p>Beneficiario/a DNI: <?php echo $this->planilla['beneficiarioDni']?></p>
    <p>Observaciones: <?php echo $this->planilla['observaciones']?></p>
</div>