<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Sistema de Fichas APROS">
        <meta name="author" content="Oficina de Cómputos Municipalidad de Lavalle">
        <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

        <title>Prestaciones Sociales</title>

        <?php
        echo $this->minifyHeadLink()
                ->prependStylesheet($this->baseUrl() . '/css/estilos.css')
                ->prependStylesheet($this->baseUrl() . '/css/bootstrap.min.css');
        ?>
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>

        <div class="container">
            <div class="row">
                <div class="col-md-3">

                </div>
                <div class="col-md-9">
                    <?php echo $this->layout()->content; ?>

                </div>
            </div>
        </div><!-- /.container -->
        <?php
        echo $this->MinifyHeadScript()
                ->appendFile($this->baseUrl() . '/js/jquery-1.10.2.min.js')
                ->appendFile($this->baseUrl() . '/js/bootstrap.min.js');
        ?>
    </body>
</html>
